### ISSUE TITLE
Keep getting this error when baking PBR

### ISSUE THREAD

**Issue by enzyme69** [oscurart/Blender-28-Addons#4]
<img width="754" alt="Screen Shot 2020-08-01 at 12 04 43 am" src="https://user-images.githubusercontent.com/3952687/89042691-b000a000-d38a-11ea-9915-a386378f1894.png">

**Comment by oscurart** [comment]
Hi @enzyme69  can attach the scene?
The error is a problem in your materials. Check this first please.

**Comment by enzyme69** [comment]
[bakepbr_july2020_003.blend.zip](https://github.com/oscurart/Blender-28-Addons/files/5007463/bakepbr_july2020_003.blend.zip)

It's all procedural material, but I also found from your Github, I downloaded all the .py and I was using the older one. But the new one also have issue.

I will test now with non procedural maybe it will work, I hope.

**Comment by enzyme69** [comment]
All PBR also give error:




<img width="1035" alt="Screen Shot 2020-08-01 at 12 28 54 am" src="https://user-images.githubusercontent.com/3952687/89044957-0fac7a80-d38e-11ea-8a1a-282c05e707b9.png">
<img width="813" alt="Screen Shot 2020-08-01 at 12 28 59 am" src="https://user-images.githubusercontent.com/3952687/89044978-1804b580-d38e-11ea-8d56-9216683a3865.png">


```
Base_Color Done!
Time elapsed (hh:mm:ss.ms) 0:00:02.057058
Render: Metallic
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/__init__.py", line 67, in load_handler
    update_sparkar_optimization_settings(bpy.context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/spark_operators_optimization.py", line 31, in update_sparkar_optimization_settings
    if context.object.modifiers.find(SPARK_DECIMATE_MODIFIER_NAME) != -1:
AttributeError: 'NoneType' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/__init__.py", line 67, in load_handler
    update_sparkar_optimization_settings(bpy.context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/spark_operators_optimization.py", line 31, in update_sparkar_optimization_settings
    if context.object.modifiers.find(SPARK_DECIMATE_MODIFIER_NAME) != -1:
AttributeError: 'NoneType' object has no attribute 'modifiers'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Info: Baking map saved to internal image, save it externally or pack it
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/__init__.py", line 67, in load_handler
    update_sparkar_optimization_settings(bpy.context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/Spark AR Toolkit/spark_operators_optimization.py", line 31, in update_sparkar_optimization_settings
    if context.object.modifiers.find(SPARK_DECIMATE_MODIFIER_NAME) != -1:
AttributeError: 'NoneType' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 327, in execute
    executePbr()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 299, in executePbr
    bake(map, "")
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 258, in bake
    oimg.colorspace_settings.name="sRGB OETF"          
TypeError: bpy_struct: item.attr = val: enum "sRGB OETF" not found in ('Filmic Log', 'Linear', 'Linear ACES', 'Non-Color', 'Raw', 'sRGB', 'XYZ')

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 327, in execute
    executePbr()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 299, in executePbr
    bake(map, "")
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/oscurart_bake_pbr.py", line 258, in bake
    oimg.colorspace_settings.name="sRGB OETF"          
TypeError: bpy_struct: item.attr = val: enum "sRGB OETF" not found in ('Filmic Log', 'Linear', 'Linear ACES', 'Non-Color', 'Raw', 'sRGB', 'XYZ')

location: <unknown location>:-1


```

**Comment by oscurart** [comment]
Okey, I'm seeing your scene
1st error, you haven't selected channels for bake
2nd error, you have "selected to active" On, but only 1 object selected.
3rd error, you are using a vector displacement like a bump.


[bakepbr_july2020_003.zip](https://github.com/oscurart/Blender-28-Addons/files/5007505/bakepbr_july2020_003.zip)




![image](https://user-images.githubusercontent.com/15130162/89044925-089b5300-d321-11ea-90fb-4a87cf909bdc.png)

**Comment by enzyme69** [comment]
I see... "selected to active" for multiple separate objects into one surface. Got that.

No vector displacement? 

I'll check the updated file.

**Comment by oscurart** [comment]
The 2nd Bug is okey!!!! have the color profiles hardcoded. I'm using the troy luts.

Try with png disabled by now!

**Comment by enzyme69** [comment]
Aha... yes it works with PNG off! So that's the culprit. 

I actually need that PNG somewhat. 

Ok will test again cheers~

**Comment by oscurart** [comment]
I'm fixing this now! give me a second...

**Comment by oscurart** [comment]
@enzyme69 
Fixed.

**Comment by enzyme69** [comment]
<img width="1042" alt="Screen Shot 2020-08-01 at 12 48 48 am" src="https://user-images.githubusercontent.com/3952687/89046765-c7db2280-d390-11ea-9ab5-f8b7ee2a4b97.png">

Thanks!!!

PBR Gold and Granite material test works~

**Comment by oscurart** [comment]
you're welcome
